# Morning Warm-up Answers- November 30th, 2020

1. Solve this function:

In [25]:
def sql_query():
    '''
    input: none
    output: string
    
    given a table named MOVIES which contains data 
    with these columns:
    
        MOVIES:
            ID, TITLE, YEAR
        
    
    write a SQL query to list all the titles and release years of all Harry Potter movies, in chronological order. 
    
    Notes: You may assume that the title of all Harry Potter movies will being with the words "Harry Potter", and 
    that if a movie title begins with the words "Harry Potter", it is a Harry Potter movie.
        
    '''
    return """ 
           SELECT title, year
           FROM movies
           WHERE title like "Harry Potter%"
           ORDER BY year;
    """

2. Solve this function:

In [26]:
def sql_query():
    '''
    input: none
    output: string
    
    given two tables named MOVIES and RATINGS which contains data 
    with these columns:
    
        MOVIES:
            ID, TITLE, YEAR
            
        RATINGS:
            MOVIE_ID, RATING, VOTES
    
    write a SQL query to list all movies released in 2010 and their ratings, 
    in descending order by rating. 
    
    Notes: For movies with the same rating, order them alphabetically by title.
        Your query should output a table with two columns, one for the title of 
        each movie and one for the rating of each movie.

        Movies that do not have ratings should not be included in the result.
    '''
    return """ 
           SELECT title, rating
           FROM movies
           JOIN ratings
               ON movies.id = ratings.movie_id
           WHERE year = 2010 AND rating IS NOT NULL
           ORDER BY rating DESC, title ASC;
    """

3. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [27]:
import numpy as np

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4. What is a term-frequency vector?<br>
   What is a inverse-document-frequency vector?

**Answer**:<br>

A term-frequency vector is a vector where each value (or column) is a unique word in the vocabulary. We are counting the time each word is used in each document and storing that in a vector, in a tf-vector we then divide each row or document by the sum total of the word counts in that row, this will turn each word count into a frequency. 

An inverse document-frequency vector is a vector whos values are constructed by taking the numerator, total number of documents in the corpus, and dividing it by the denominator, which is the count of documents that each word appears. 


**NOTE**: you might see on the assessment that they mention calculating the unnormalized versions of each respective vector, that just means without including the division

5. There are three artists entering a talent show: Pam, Pia, and Pablo. 
    * Pam put in 15 paintings, 4% of her works have won First Prize
    * Pia put in 5 paintings, 6% of her works have won First Prize
    * Pablo put in 10 paintings, 3% of his works have won First Prize.
    
Which artist is the most likely to win?<br>
What is that artist's probability of winning?<br>

(Hint: Bayes theorem)

**Answer**:<br>

$ P(First) = P(Pam) * P(First|Pam) + P(Pia) * P(First|Pia) + P(Pablo) * P(First|Pablo) $
$ P(First) = 0.04 $

**P(Pam|First)**:<br>
$ P(Pam|First) = \frac{P(Pam) * P(First|Pam)}{P(First)}$<br>
$ P(Pam|First) = \frac{(15/30) * 0.04)}{0.04}$<br>
$ P(Pam|First) = \frac{0.5*0.04}{0.04}$<br>
$ P(Pam|First) = \frac{0.02}{0.04}$<br>
$ P(Pam|First) = 50 \% $

**P(Pia|First)**:<br>
$ P(Pia|First) = \frac{P(Pia) * P(First|Pia)}{P(First)}$<br>
$ P(Pia|First) = \frac{(5/30) * 0.06)}{0.04}$<br>
$ P(Pia|First) = \frac{0.167*0.06}{0.04}$<br>
$ P(Pia|First) = \frac{0.01}{0.04}$<br>
$ P(Pia|First) = 25 \% $

**P(Pablo|First)**:<br>
$ P(Pablo|First) = \frac{P(Pablo) * P(First|Pablo)}{P(First)}$<br>
$ P(Pablo|First) = \frac{(10/30) * 0.03)}{0.04}$<br>
$ P(Pablo|First) = \frac{0.333*0.03}{0.04}$<br>
$ P(Pablo|First) = \frac{0.01}{0.04}$<br>
$ P(Pablo|First) = 25 \% $