# Quick NumPy examples

1. How to stack two arrays horizontally?<br>
    Q. Stack the arrays a and b horizontally.

Input:

In [2]:
import numpy as np
a = np.arange(10).reshape(2,-1); a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
b = np.arange(10).reshape(2, -1); b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Desired Output:

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [5]:
#Solution 1: np.concatenate
# Documentation: https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html
np.concatenate([a, b], axis = 1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [6]:
#Solution 2: np.hstack
# Documentation: https://numpy.org/doc/stable/reference/generated/numpy.hstack.html
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [7]:
#Solution 3: np.c_
# Documentation: https://numpy.org/doc/stable/reference/generated/numpy.c_.html
np.c_[a, b]

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

2. How to add columns to a matrix in python by utilizing NumPy.

In [19]:
import numpy as np

X = np.random.uniform(size=(5,3))
X

array([[0.7163272 , 0.28940609, 0.18319136],
       [0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797],
       [0.73519402, 0.96218855, 0.24875314],
       [0.57615733, 0.59204193, 0.57225191]])

In [20]:
n, m = X.shape
X0 = np.ones((n, 1))
ans = np.hstack((X, X0))
ans

array([[0.7163272 , 0.28940609, 0.18319136, 1.        ],
       [0.58651293, 0.02010755, 0.82894003, 1.        ],
       [0.00469548, 0.67781654, 0.27000797, 1.        ],
       [0.73519402, 0.96218855, 0.24875314, 1.        ],
       [0.57615733, 0.59204193, 0.57225191, 1.        ]])

3. Let's say you have a dataframe, that contains four columns:
    * `a`, `b`, `c` which are your feature columns
    * `target` which is your target column, or dependent variable.<br>

You then are given an additional array, `d`, that is to be inputted into the dataframe as a feature column. Once added in, separate the columns into your X, input variables, and y, your output variable. Utilize NumPy so that these variables are able to be inputted into scikit-learns LinearRegression model.

In [11]:
import pandas as pd

np.random.seed(0)
df1 = pd.DataFrame(np.random.randn(10, 4), columns=['a', 'b', 'c', 'target']) 
df1.head(2)

a         b         c    target
0  1.764052  0.400157  0.978738  2.240893
1  1.867558 -0.977278  0.950088 -0.151357

In [9]:
# Feature Column:
d = np.random.randn(10); d

array([-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
       -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028])

In [12]:
# Now let's add this feature column to our already existing dataframe.

df1['d'] = d

# We can reorder the columns so it makes a little more sense

df1 = df1[['a','b','c','d','target']]
df1.head(2)

a         b         c         d    target
0  1.764052  0.400157  0.978738 -1.048553  2.240893
1  1.867558 -0.977278  0.950088 -1.420018 -0.151357

In [13]:
# Now let's create our X and y variables in order to input into our scikit learn models

X = df1.drop('target', axis = 1).to_numpy()
X

array([[ 1.76405235,  0.40015721,  0.97873798, -1.04855297],
       [ 1.86755799, -0.97727788,  0.95008842, -1.42001794],
       [-0.10321885,  0.4105985 ,  0.14404357, -1.70627019],
       [ 0.76103773,  0.12167502,  0.44386323,  1.9507754 ],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.50965218],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.4380743 ],
       [ 2.26975462, -1.45436567,  0.04575852, -1.25279536],
       [ 1.53277921,  1.46935877,  0.15494743,  0.77749036],
       [-0.88778575, -1.98079647, -0.34791215, -1.61389785],
       [ 1.23029068,  1.20237985, -0.38732682, -0.21274028]])

In [14]:
y = df1['target'].values
y

array([ 2.2408932 , -0.15135721,  1.45427351,  0.33367433, -0.85409574,
       -0.74216502, -0.18718385,  0.37816252,  0.15634897, -0.30230275])

In [15]:
from sklearn.linear_model import LinearRegression

# Now we can create our LinearRegression model and fit our X and y.
linear_model = LinearRegression()
linear_model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)